export { default as Banner } from "./banner/Banner";
export { default as Customer } from "./customer/Customer";
export { default as Footer } from "./footer/Footer";
export { default as Header } from "./header/Header";
export { default as Hero } from "./hero/Hero";
export { default as Share } from "./share/Share";
export { default as Vendor } from "./vendor/Vendor";
export { default as TestimonyTwo } from "./testimonyTwo/TestimonyTwo";
export { default as TestimonyOne } from "./testimonyOne/TestimonyOne";
